language: python
python:
- '2.7'
services:
- docker
install:
- pip install .
before_script:
- docker run -d --name jaeger -p 5775:5775/udp -p 5778:5778 -p 14268:14268 -p 6831:6831/udp
  -p 6832:6832/udp -p 16686:16686 jaegertracing/all-in-one:latest
script:
- pytest
deploy:
  - provider: pypi
    skip_cleanup: true
    user: platform9
    password:
      secure: PjumHXO1GR+V4Deeii1grOMlXTSkPPze+99HnayCi7TEX3wYXkcBxmF75PNr+i551ns/zSJcRh48lBgp0FKly/gP7hXUgqgaealRQ9EYIA4Tv3kE+nxvanBw5EQ0IbPt5pXzf1EgVzZz7CgxFZmoMMAKnjjo2bWe0mA528+YVrMv7O3QIMPbYhQ+/XUpPv6i7eeA/Q6bOu0EsE8P3bTSfHhuoAB871+cBiaH1bKe7pZiqG8QzY8I2U6+3Rd7NA742voj2ZgF8P9jNwHhW7xG2vw2DulO4tO94po/2qMDovH6p0alj9fc+adPYmz808qGUPCR6HJhSnUjtu1dwenAwXXtEMxFiVL5fG6gC3w5B3AwytWO1g17sG0KaaOeMQnTQTIaqZJ6U5AdOUKt29b4+9gWs6jgbXIgRNDoXJ7RPapSrOxNVRhJq9Yrpg1CoIdNIMR2CWSxMuSfYrpOnNWEPgt2ZmSuvRjuLmHtcRAlO/ovUsiESDELbIutiUDLEMME+/zVovX+KZOcWw1/NGDupkAZlxr8703IGyGc1Uky2I+Ne7cZgS02k3dOL+vwrpkKLsPN46fL8HlGZyk3+wYygD6p5brTHpzY9iqu3zEVF30bmyA4MmGgPffHiNVHOppiyq11HnV3B1+sQ8Qq6x3mkXJbxtoU+ePb3VAxn5HNYPw=
    on:
      branches:
      - ver-0.1
      - ver-0.2
